#install.packages("psych")
#library(psych)

test_is_bodyaccx<-read.table("./UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt")
test_is_bodyaccy<-read.table("./UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt")
test_is_bodyaccz<-read.table("./UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt")
test_is_bodygyrox<-read.table("./UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt")
test_is_bodygyroy<-read.table("./UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt")
test_is_bodygyroz<-read.table("./UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt")
test_is_totalaccx<-read.table("./UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt")
test_is_totalaccy<-read.table("./UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt")
test_is_totalaccz<-read.table("./UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt")
test_subject_test<-read.table("./UCI HAR Dataset/test/subject_test.txt")
test_x_test<-read.table("./UCI HAR Dataset/test/X_test.txt")
test_y_test<-read.table("./UCI HAR Dataset/test/y_test.txt")


train_is_bodyaccx<-read.table("./UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt")
train_is_bodyaccy<-read.table("./UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt")
train_is_bodyaccz<-read.table("./UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt")
train_is_bodygyrox<-read.table("./UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt")
train_is_bodygyroy<-read.table("./UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt")
train_is_bodygyroz<-read.table("./UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt")
train_is_totalaccx<-read.table("./UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt")
train_is_totalaccy<-read.table("./UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt")
train_is_totalaccz<-read.table("./UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt")
train_subject_train<-read.table("./UCI HAR Dataset/train/subject_train.txt")
train_x_train<-read.table("./UCI HAR Dataset/train/X_train.txt")
train_y_train<-read.table("./UCI HAR Dataset/train/y_train.txt")


is_bodyaccx<-merge(test_is_bodyaccx,train_is_bodyaccx,all=T)
is_bodyaccy<-merge(test_is_bodyaccy,train_is_bodyaccy,all=T)
is_bodyaccz<-merge(test_is_bodyaccz,train_is_bodyaccz,all=T)
is_bodygyrox<-merge(test_is_bodygyrox,train_is_bodygyrox,all=T)
is_bodygyroy<-merge(test_is_bodygyroy,train_is_bodygyroy,all=T)
is_bodygyroz<-merge(test_is_bodygyroz,train_is_bodygyroz,all=T)
is_totalaccx<-merge(test_is_totalaccx,train_is_totalaccx,all=T)
is_totalaccy<-merge(test_is_totalaccy,train_is_totalaccy,all=T)
is_totalaccz<-merge(test_is_totalaccz,train_is_totalaccz,all=T)
subject<-merge(test_subject_test,train_subject_train,all=T)
x<-merge(test_x_test,train_x_train,all=T)
y<-merge(test_y_test,train_y_train,all=T)

describe(is_bodyaccx)
describe(is_bodyaccy)
describe(is_bodyaccz)
describe(is_bodygyrox)
describe(is_bodygyroy)
describe(is_bodygyroz)
describe(is_totalaccx)
describe(is_totalaccy)
describe(is_totalaccz)
describe(subject)
describe(x)
describe(y)

